title: Page
pages: true
files: true
fields:
  title:
    label: Title
    type:  text
  text:
    label: Text
    type:  textarea
  pageicon:
    label: Page icon
    type:  selector
    mode:  single
    types:
        - image
